accounts/urls.py
#
# Copyright (C) 2019 Guillaume Bernard <guillaume.bernard@koala-lms.org>
# Copyright (C) 2020 Louis Barbier <louis.barbier41@outlook.fr>
#
# This file is part of Koala LMS (Learning Management system)

# Koala LMS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# We make an extensive use of the Django framework, https://www.djangoproject.com/
from django.contrib.auth.views import PasswordResetView
from django.urls import path, include, re_path

from accounts import views
from accounts.forms import UserPasswordResetForm

app_name = 'accounts'

ajax_api_urlpatterns = [
    path('search/', views.search_user, name='ajax/search'),
    path('notification/read/<int:notification_id>',
         views.notification_mark_as_read, name="ajax/notification/read"),
    path('notification/delete/<int:notification_id>',
         views.notification_delete, name="ajax/notification/delete"),
]

urlpatterns = [
    path('', views.LoginView.as_view(), name='index'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('login_success/', views.loginSuccess, name='login_success'),
    path('details/', views.AccountsDetailsView.as_view(), name='details'),

    #  Password update and reset
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_reset/', PasswordResetView.as_view(
        form_class=UserPasswordResetForm), name="password_reset"),

    path('preferences/', views.preferences, name='preferences'),

    #  Account registration and activation
    path('register/', views.AccountsRegisterView.as_view(), name='register'),
    re_path(
        r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'
    ),
    re_path(
        r'send_activation_mail/(?P<uidb64_username>[0-9A-Za-z_\-]+)/$', views.resend_activation_mail,
        name='resend_email_confirmation'
    ),

    #  Ajax views
    path('ajax/', include(ajax_api_urlpatterns))
]

lms/urls.py
#
# Copyright (C) 2019 Guillaume Bernard <guillaume.bernard@koala-lms.org>
#
# This file is part of Koala LMS (Learning Management system)

# Koala LMS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# We make an extensive use of the Django framework, https://www.djangoproject.com/
#

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name="home"),

    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('learning/', include('learning.urls', namespace='learning')),

    # Extra dependencies
    path('markdownx/', include('markdownx.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
#
# Copyright (C) 2019 Guillaume Bernard <guillaume.bernard@koala-lms.org>
#
# This file is part of Koala LMS (Learning Management system)

# Koala LMS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# We make an extensive use of the Django framework, https://www.djangoproject.com/

import django.contrib.auth.forms as auth_forms
from django.contrib.auth import authenticate
from django.forms import Form
from django import forms
from .models import Person


class CustomClassesOnFormMixin(Form):
    custom_classes = ["form-control"]

    def __init__(self, *args, **kwargs):
        super(CustomClassesOnFormMixin, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': ' '.join(self.custom_classes)})


class UserLoginForm(CustomClassesOnFormMixin, auth_forms.AuthenticationForm):

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(
                self.request, username=username, password=password)
            if self.user_cache is None:
                try:
                    self.user_cache = Person.objects.get(username=username)
                except Person.DoesNotExist:
                    self.user_cache = None

                if self.user_cache is not None and self.user_cache.check_password(password):
                    self.confirm_login_allowed(self.user_cache)
                else:
                    self.get_invalid_login_error()

        return self.cleaned_data


class UserPasswordResetForm(CustomClassesOnFormMixin, auth_forms.PasswordResetForm):
    pass


class UserCreationForm(CustomClassesOnFormMixin, auth_forms.UserCreationForm):
    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2')


class UserChangeForm(CustomClassesOnFormMixin, auth_forms.UserChangeForm):
    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'email', 'preferred_language')


class UserAdminChangeForm(CustomClassesOnFormMixin, auth_forms.UserChangeForm):
    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'email', 'preferred_language')

accounts/views.py
#
# Copyright (C) 2019 Guillaume Bernard <guillaume.bernard@koala-lms.org>
#
# This file is part of Koala LMS (Learning Management system)

import urllib
from django import template
from accounts.tokens import account_activation_token
from accounts.models import Person, Notification, Preferences
from accounts.forms import UserLoginForm, UserCreationForm, UserChangeForm
from django.views.generic import CreateView, UpdateView
from django.contrib import messages
# Koala LMS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# We make an extensive use of the Django framework, https://www.djangoproject.com/
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as AuthLoginView, PasswordChangeView
from django.core.mail import EmailMessage
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.translation import ugettext_lazy as _
from django.core import serializers

pref_dict = {
    'Development': ['Web Development', 'Data Science', 'Mobile Apps', 'Programming Languages', 'Game Development', 'Databases', 'Software Testing', 'Software Engineering', 'Development Tools', 'E Commerce'],
    'Business': ['Finance Courses', 'Entrepreneurship', 'Communications', 'Management', 'Sales', 'Strategy', 'Operations', 'Project Management', 'Business Law', 'Data And Analytics', 'Home Business', 'Human Resources', 'Industry', 'Media', 'Real Estate', 'Other Business'],
    'Finance And Accounting': ['Accounting Bookkeeping', 'Compliance', 'Cryptocurrency And Blockchain', 'Economics', 'Finance Management', 'Finance Certification And Exam Prep', 'Financial Modeling And Analysis', 'Investing And Trading', 'Money Management Tools', 'Taxes', 'Other Finance And Accounting'],
    'It And Software': ['It Certification', 'Network And Security', 'Hardware', 'Operating Systems', 'Other It And Software'],
    'Office Productivity': ['Microsoft', 'Apple', 'Google', 'Sap', 'Oracle', 'Other Productivity'],
    'Personal Development': ['Personal Transformation', 'Productivity', 'Leadership', 'Personal Finance', 'Career Development', 'Parenting And Relationships', 'Happiness', 'Religion And Spirituality', 'Personal Brand Building', 'Creativity', 'Influence', 'Self Esteem', 'Stress Management', 'Memory', 'Motivation', 'Other Personal Development'],
    'Design': ['Web Design', 'Graphic Design', 'Design Tools', 'User Experience', 'Game Design', 'Design Thinking', '3D And Animation', 'Fashion', 'Architectural Design', 'Interior Design', 'Other Design'],
    'Marketing': ['Digital Marketing', 'Search Engine Optimization', 'Social Media Marketing', 'Branding', 'Marketing Fundamentals', 'Analytics And Automation', 'Public Relations', 'Advertising', 'Video And Mobile Marketing', 'Content Marketing', 'Growth Hacking', 'Affiliate Marketing', 'Product Marketing', 'Other Marketing'],
    'Lifestyle': ['Arts And Crafts', 'Food And Beverage', 'Beauty And Makeup', 'Travel', 'Gaming', 'Home Improvement', 'Pet Care And Training', 'Other Lifestyle'],
    'Photography': ['Digital Photography', 'Photography Fundamentals', 'Portraits', 'Photography Tools', 'Commercial Photography', 'Video Design', 'Other Photography'],
    'Health And Fitness': ['Fitness', 'General Health', 'Sports', 'Nutrition', 'Yoga', 'Mental Health', 'Dieting', 'Self Defense', 'Safety And First Aid', 'Dance', 'Meditation', 'Other Health And Fitness'],
    'Music': ['Instruments', 'Production', 'Music Fundamentals', 'Vocal', 'Music Techniques', 'Music Software', 'Other Music'],
    'Teaching And Academics': ['Engineering', 'Humanities', 'Math', 'Science', 'Online Education', 'Social Science', 'Language', 'Teacher Training', 'Test Prep', 'Other Teaching Academics']
}

pref_values = tuple(pref_dict.keys())


def _update_valid_or_invalid_form_fields(form):
    for field in form.fields:
        try:
            current_class = form.fields[field].widget.attrs['class']
        except KeyError:
            current_class = str()

        if field in form.errors:
            form.fields[field].widget.attrs.update(
                {'class': current_class + ' ' + 'is-invalid'})
        elif field in form.changed_data:
            form.fields[field].widget.attrs.update(
                {'class': current_class + ' ' + 'is-valid'})
    return form


def loginSuccess(request):
    if request.method == 'GET':
        current_user = request.user
        if current_user.is_first_login:
            return redirect("accounts:preferences")
    return redirect("home")


def send_activation_mail(user: get_user_model(), domain: str) -> bool:
    """
    This function sends an activation email. It can be used to send the first confirmation email or to send a new one

    :param user: This contains the user who wants activate his account
    :type user: get_user_model()
    :param domain: the domain on which the current instance is running. This is, for instance: demo.koala-lms.org
    :type domain: str
    :return True if the mail has been send
    :rtype bool
    """
    message = render_to_string('registration/account_activation_mail.html', {
        'user': user,
        'domain': domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
    })
    return EmailMessage(_("Activate your Koala LMS account"), message, to=[user.email]).send() == 1


def resend_activation_mail(request, uidb64_username: str):
    """
    This view is used to resent the confirmation email to the user that requested it.

    :param request: the request to handle
    :type request: django.http.HttpRequest
    :param uidb64_username: the user’s username to send the confirmation email. username is encoded using urlsafe_base64_encode
    :type uidb64_username: str
    """
    try:
        decoded_user = get_object_or_404(get_user_model(), username=force_text(
            urlsafe_base64_decode(uidb64_username)))
    except(TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
        messages.error(
            request,
            _("Something went wrong when trying to find your account in the database. Aborting.")
        )
    else:
        if send_activation_mail(decoded_user, request.get_host()):
            messages.info(
                request, _(
                    "%(user)s, we send you a new confirmation email to %(email)s."
                ) % {'user': decoded_user.get_full_name(), 'email': decoded_user.email}
            )
        else:
            messages.error(
                request, _("The component used to send the confirmation mails is broken. Please contact your "
                           "system administrator to let him fix this issue.")
            )
    return redirect("accounts:login")


class LoginView(AuthLoginView):
    form_class = UserLoginForm
    redirect_authenticated_user = True

    def form_invalid(self, form):
        if not self.request.user.is_active:
            # If the error code is 'inactive' we propose to the user sending a new confirmation's email
            user = urlsafe_base64_encode(force_bytes(form.user_cache.username))
            messages.warning(
                self.request,
                _("%(name)s, is seems your account has not been activated yet. If you did not received any "
                  "confirmation email, click <a href=\"%(resend_link)s\">here</a>. Another one will be resend "
                  "to you.")
                % {
                    'name': form.user_cache.get_full_name(),
                    'resend_link': reverse_lazy('accounts:resend_email_confirmation', kwargs={'uidb64_username': user})
                }
            )
        return super().form_invalid(form)


class PasswordChange(PasswordChangeView):
    success_url = reverse_lazy('accounts:details')
    title = _("My account − Change password")

    def form_valid(self, form):
        messages.success(self.request, _("Password updated!"))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _(
            "Error when updating password. You should fix the issues and try again."))
        form = _update_valid_or_invalid_form_fields(form)
        return super().form_invalid(form)


class AccountsRegisterView(CreateView):
    template_name = "accounts/register.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("accounts:details")
    extra_context = {
        "title": _("Create a new account")
    }

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        if send_activation_mail(user, self.request.get_host()):
            messages.success(
                self.request, _(
                    "%(user)s (%(username)s), your registration is complete now. In order to access your account, you "
                    "have to activate it first. We just sent you an email to confirm your registration."

accounts/templates/accounts/authentication_base.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block title %}
  {% if user.is_authenticated %}
    {% trans "Access denied" %}
  {% else %}
    {{ title }}
  {% endif %}
{% endblock %}

{% block accounts_content %}
  {# User is already authenticated, so do not show anything about authentication or registration #}
  {% if user.is_authenticated %}
    <div class="card">
      <div class="card-header">
        <h4 class="card-title mb-1 mt-1">{% trans "Access denied" %}</h4>
      </div>
      <div class="card-body">
        <div class="text-center">
          <p>
            {% blocktrans trimmed with name=user.display_name %}
              You are already logged in as <strong>{{ name }}</strong>. Thus, you <strong>cannot</strong> perform this
              operation.
            {% endblocktrans %}
          </p>
          <p>{% trans "You will be redirected in a few seconds…" %}</p>
          <script type="text/javascript">
            setTimeout(function () {
              window.location.href = "{% url 'accounts:details' %}";
            }, 5000);
          </script>
        </div>
        <hr>
        <div class="row justify-content-center">
          <a href="{% url 'accounts:details' %}" class="btn btn-outline-secondary m-1">{% trans "My details" %}</a>
        </div>
      </div>
    </div>
  {% else %}
    {% block accounts_actionblock %}{% endblock %}
  {% endif %}
{% endblock %}

accounts/templates/accounts/base.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{{ title }}{% endblock %}

{% block extrastyle %}{{ block.super }}
  <link rel="stylesheet" href="{% static 'accounts/style.css' %}"/>
  <script defer src="{% static 'accounts/js/notification.js' %}"></script>
  <script defer src="{% static 'accounts/fonts/fontawesome.js' %}"></script>
{% endblock %}

{% block extrahead %}
  <link rel="shortcut icon" href="{% static 'accounts/images/favicon.png' %}" type="image/x-icon">
{% endblock %}

{% block content %}
  {% include "accounts/_includes/messages.html" %}
  {% block accounts_content %}{% endblock %}
{% endblock %}

accounts/templates/accounts/details.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block accounts_content %}
  <div class="card">
    <div class="card-header">
      <h4 class="card-title mb-1 mt-1">{% trans "Personal information" %}</h4>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        <div class="form-row">
          <div class="col-md-6">
            {% include "accounts/_includes/basic_block.html" with field=form.first_name %}
          </div>
          <div class="col-md-6">
            {% include "accounts/_includes/basic_block.html" with field=form.last_name %}
          </div>
        </div>
        {% include "accounts/_includes/basic_block.html" with field=form.email icon="fa-at" %}
        {% include "accounts/_includes/basic_block.html" with field=form.preferred_language icon="fa-flag" %}
        <button type="submit" class="btn btn-primary float-right">
          {% trans "Update personnal information" %}
        </button>
      </form>
    </div>
  </div>

  <div class="card mt-3">
    <div class="card-header">
      <a href="{% url 'accounts:password_change' %}" class="float-right btn btn-outline-primary">
        {% trans "Change password" %}
      </a>
      <h4 class="card-title mb-1 mt-1">{% trans "Password" %}</h4>
    </div>
  </div>

  <div class="card mt-3">
    <div class="card-header">
      <h4 class="card-title mb-1 mt-1">{% trans "Groups" %}</h4>
    </div>
    <div class="card-body">
      {% if user.groups.count > 0 %}
        {% blocktrans with groups=user.groups.all|join:', ' count nb=user.groups.count %}
          You are registered in the group: <i>{{ groups }}</i>.
        {% plural %}
          You are registered in the groups: <i>{{ groups }}</i>.
        {% endblocktrans %}
      {% else %}
        {% trans "You are not registered in any group yet." %}
      {% endif %}
    </div>
  </div>

{% endblock %}

accounts/templates/accounts/dropdown.html
{% load i18n static %}

<!-- Notifications -->
{% if user.is_authenticated %}
  <script defer src="{% static 'accounts/js/notification.js' %}"></script>
  <li class="nav-item dropdown">
    <a class="nav-link" href="#" id="notifications_dropdown_link" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-bell"></i>
      {% if user.unread_notifications.count > 0 %}
        <span class="badge badge-danger align-middle" id="notification_counter">
        {{ user.unread_notifications.count }}
      </span>
      {% endif %}
    </a>
    {% if user.notifications.count > 0 %}
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="notifications_dropdown_link"
           id="notifications_dropdown">
        {% for notification in user.notifications.all %}

          {% if forloop.counter0 != 0 %}
            <div class="dropdown-divider" id="notification_divider_{{ notification.id }}"></div>
          {% endif %}

          <div class="px-3" id="notification_{{ notification.id }}">

            {# The notification content and buttons to mark as read or delete #}
            <div class="row" style="min-width: 25rem !important;">

              {# Notification message #}
              <div class="col-10 pr-0">
                <p class="small {% if notification.is_read %}text-muted{% endif %} text-justify"
                   id="notification_{{ notification.id }}_message">
                  {{ notification.message }}
                </p>
              </div>

              {# Buttons to mark the notification as read or to delete it #}
              <div class="btn-group-vertical col-auto pr-0">
                {% csrf_token %}
                {% if not notification.is_read %}
                  <a onclick="notification_mark_as_read({{ notification.id }})" class="btn btn-sm"
                     id="notification_{{ notification.id }}_mark_as_read_btn">
                    <i class="fa fa-eye-slash"></i>
                  </a>
                {% endif %}
                <a onclick="notification_delete({{ notification.id }})" class="btn btn-sm"
                   id="notification_{{ notification.id }}_delete_btn">
                  <i class="fa fa-times"></i>
                </a>
              </div>
            </div>

            {# The notification timestamp and target link #}
            <div class="clearfix">
              <span class="small float-left"><i class="fa fa-clock pr-1"></i> {{ notification.timestamp | date }}</span>
              {% if notification.target %}
                <a class="small float-right" href="{{ notification.target }}"
                   data-toggle="tooltip" data-placement="left"
                   title="{% blocktrans with url=notification.target %}Go to {{ url }}{% endblocktrans %}">
                  <i class="fa fa-link pr-1"></i>{% trans "Access item" %}
                </a>
              {% endif %}
            </div>

          </div>
        {% endfor %}
      </div>
    {% endif %}
  </li>
{% endif %}
<!-- End of notifications -->

<!-- User account -->
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="accounts_dropdown" data-toggle="dropdown"
     aria-haspopup="true" aria-expanded="false">
    {% if user.is_authenticated %}
      {{ user.display_name }}
    {% else %}
      {% trans "Log in" %}
    {% endif %}
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="accounts_dropdown">
    {% if user.is_authenticated %}
      <a class="dropdown-item"
         href="{% url 'accounts:details' %}">{% trans "My details" %}</a>
      <a class="dropdown-item" href="{% url 'logout' %}">{% trans "Log out" %}</a>
    {% else %}
      <a class="dropdown-item" href="{% url 'accounts:login' %}">{% trans "Log in" %}</a>
      <a class="dropdown-item"
         href="{% url 'accounts:register' %}">{% trans "Create a new account" %}</a>
    {% endif %}
  </div>
</li>
<!-- End of user account -->

accounts/templates/accounts/register.html
{% extends 'accounts/authentication_base.html' %}
{% load i18n %}

{% block accounts_actionblock %}
  <div class="card">
    <div class="card-header">
      <a href="{% url 'accounts:login' %}" class="float-right btn btn-outline-primary">{% trans "Sign in" %}</a>
      <h4 class="card-title mb-1 mt-1">{% trans "Create a new account" %}</h4>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}

        <h5>{% trans "About you…" %}</h5>
        <div class="form-row">
          <div class="col-md-6">
            {% include "accounts/_includes/basic_block.html" with field=form.first_name %}
          </div>
          <div class="col-md-6">
            {% include "accounts/_includes/basic_block.html" with field=form.last_name %}
          </div>
        </div>

        <h5>{% trans "Your credential information…" %}</h5>
        {% include "accounts/_includes/basic_block.html" with field=form.username icon="fa-user" %}
        {% include "accounts/_includes/basic_block.html" with field=form.email icon="fa-at" %}

        <div class="form-row">
          <div class="col-md-6">
            {% include "accounts/_includes/password_block.html" with password=form.password1 %}
          </div>
          <div class="col-md-6">
            {% include "accounts/_includes/password_block.html" with password=form.password2 %}
          </div>
        </div>

        <button type="submit" class="btn btn-primary float-right">{% trans "Create the new account" %}</button>
      </form>
    </div>
  </div>
{% endblock %}